In [5]:
import numpy as  np
import matplotlib.pyplot as plt

In [6]:
class Neural_Network(object):
    def __init__(self):
        # Define HyperParameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
 
        # Weights (parameters)
        self.W1 = np.random.rand(self.inputLayerSize, \
                                 self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, \
                                  self.outputLayerSize)
    def forward(self, X):
        # Propogate inputs through net
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def sigmoidPrime(self, z):
        return np.exp(-z) / ((1 + np.exp(-z)) ** 2)

    def costFunction(self, X, y):
        self.yHat = self.forward(X)
        J = 0.5 * sum((y - self.yHat) ** 2)
        return J
    
    def costFunctionPrime(self, X, y):
        self.yHat = self.forward(X)
        delta3 = np.multiply(-(y - self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
    
        delta2 = np.dot(delta3, self.W2.T) * self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)
    
        return dJdW1, dJdW2
    

In [7]:
X = np.array([[3, 5], [5, 1], [10, 2]])
y = np.array([[0.75], [0.82], [0.93]])

In [15]:
NN = Neural_Network()

In [16]:
yHat = NN.forward(X)
yHat  

array([[0.60916298],
       [0.57702975],
       [0.61053011]])

In [17]:
NN.W1[0, 0] = 1.1
yHat = NN.forward(X)
np.sum(0.5 * (y - yHat) ** 2)

0.07407384984361265

In [18]:
def sigmoidPrime(z):
    return np.exp(-z) / ((1 + np.exp(-z)) ** 2)

In [20]:
cost1 = NN.costFunction(X, y)

In [21]:
dJdW1, dJdW2 = NN.costFunctionPrime(X, y)

In [22]:
dJdW1

array([[-0.00102463, -0.00057621,  0.00080427],
       [-0.0007992 , -0.00013693,  0.00034135]])

In [23]:
dJdW2

array([[-0.14730926],
       [-0.14413047],
       [-0.14722981]])

In [24]:
scalar = 3
NN.W1 = NN.W1 + scalar * dJdW1
NN.W2 = NN.W2 + scalar * dJdW2
cost2 = NN.costFunction(X, y)

In [25]:
cost1, cost2

(array([0.07407385]), array([0.41831272]))

In [26]:
dJdW1, dJdW2 = NN.costFunctionPrime(X, y)
NN.W1 = NN.W1 - scalar * dJdW1
NN.W2 = NN.W2 - scalar * dJdW2
cost3 = NN.costFunction(X, y)

In [27]:
cost2, cost3

(array([0.41831272]), array([0.01415151]))

In [28]:
def f(x):
    return x ** 2

In [29]:
epsilon = 1e-4
x = 1.5

In [30]:
numericGradient = (f(x + epsilon) - f(x-epsilon)) / (2 * epsilon)

In [32]:
numericGradient, 2*x

(2.9999999999996696, 3.0)